apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default # Cambia esto al namespace adecuado si no es 'default'
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
