apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  custom-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "uid": null,
        "title": "Prometheus Pods Log",
        "tags": [],
        "timezone": "browser",
        "schemaVersion": 16,
        "version": 0,
        "annotations": {
          "list": []
        },
        "panels": [
          {
            "title": "Example Panel",
            "type": "graph",
            "datasource": "Prometheus",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])",
                "interval": "",
                "legendFormat": "{{pod}}",
                "refId": "A"
              }
            ]
          }
        ]
      }
    }
